### ISSUE TITLE
How should we add the license to the repositories?

### ISSUE THREAD

**Issue by zimmski** [go-clang/design#2]
What is the proper way of linking to the https://github.com/go-clang/license repository? Or should we additionally add the license to all repositories?

**Comment by sbinet** [comment]
for `gonum`, we do it like that: https://github.com/gonum/plot/blob/master/LICENSE or just by mentionning it in the master readme: https://github.com/gonum/matrix

or, perhaps, do it like the `golang.org/x/...` repos:
 https://github.com/golang/exp/blob/master/AUTHORS
 https://github.com/golang/exp/blob/master/CONTRIBUTORS
 https://github.com/golang/exp/blob/master/LICENSE

I'd err on the safe side and would put `{LICENSE,AUTHORS,CONTRIBUTORS}` files in our repositories with content redirecting to the `go-clang/license` repository.

**Comment by zimmski** [comment]
So adding a section to the README and files similar to the `LICENSE` file in `gonum`?

**Comment by sbinet** [comment]
yes:
- add a section to the `README` stating it's released under a BSD-3 license and a link to the `go-clang/license` repo
- add `LICENSE`, `AUTHORS` and `CONTRIBUTORS` with content redirecting to `github.com/go-clang/license/xyz`

**Comment by zimmski** [comment]
License information got merged for go-clang/bootstrap and go-clang/gen so I am closing this issue.

And I will try to use "license" instead of the British "licence". Never noticed it before :-)
