### ISSUE TITLE
More user-friendly linking to libclang

### ISSUE THREAD

**Issue by zimmski** [go-clang/design#3]
@marxriedl and I are out of ideas on how to solve the following problems:

a.) We are currently using `-lclang` to link libclang into the binding. This was also done in the original go-clang source code. However, this does not work with all Linux distributions (I have no idea about MacOSX and Windows btw) e.g. openSUSE has only "libclang.so.MAJOR.MINOR" and on TravisCI it is called `libclang.so.1` which makes it necessary to create a symlink. This is not really user-friendly.

b.) We are also using `llvm-config` which sometimes does not exist because it is not installed or it has a version suffix.

**Comment by sbinet** [comment]
perhaps have a `go run make.go [configure]` script which will generate a `cgoflags_gen.go` file with the appropriate C incantations:

``` sh
sh> go run ./make.go # or even just a `go generate` ?
sh> cat cgoflags_gen.go
```

``` go
package clang

// #cgo CFLAGS: -I/path/extracted/from/llvm-config
// #cgo LDFLAGS: -L/path/from/llvm-config -l:libclang.so[.MAJOR[.MINOR]]
import "C"
```

**Comment by zimmski** [comment]
I would like to see a go-getable solution but I really see no possible solution besides talking to distribution package owners. I think it is OK to have some Go code which replaces the `cgoflags.go` file. So I guess we just open up an issue for that?

**Comment by sbinet** [comment]
done: go-clang/gen#102
